<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DUBN34630627A" failures="2" tests="3" name="com.james.training.selenium_project.uielementspagetests.AlertsSoftAssertsTests" time="35.806" errors="0" timestamp="13 Dec 2019 17:48:57 GMT" skipped="0">
  <testcase classname="com.james.training.selenium_project.uielementspagetests.AlertsSoftAssertsTests" name="jsPromptTest" time="13.000"/>
  <testcase classname="com.james.training.selenium_project.uielementspagetests.AlertsSoftAssertsTests" name="jsAlertTest" time="11.404">
    <failure message="The following asserts failed:
	Alert message is not expected. 
Should be &#039;I am a JS Alert&#039;, but it is &#039;I am a JS Alert[Fail]&#039; expected [true] but found [false],
	result is not expected. 
Should be &#039;You successfuly clicked an alert&#039;, but it is &#039;You successfuly clicked an alert[Fail]&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:Alert message is not expected. Should be 'I am a JS Alert', but it is 'I am a JS Alert[Fail]' expected [true] but found [false],result is not expected. Should be 'You successfuly clicked an alert', but it is 'You successfuly clicked an alert[Fail]' expected [true] but found [false]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.james.training.selenium_project.uielementspagetests.AlertsSoftAssertsTests.jsAlertTest(AlertsSoftAssertsTests.java:51)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- jsAlertTest -->
  <testcase classname="com.james.training.selenium_project.uielementspagetests.AlertsSoftAssertsTests" name="jsDismissTest" time="11.402">
    <failure message="The following asserts failed:
	Alert message is not expected. 
Should be &#039;I am a JS Confirm&#039;, but it is &#039;I am a JS Confirm[Fail]&#039; expected [true] but found [false],
	result is not expected. 
Should be &#039;You clicked: Cancel&#039;, but it is &#039;You clicked: Cancel[Fail]&#039; expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:Alert message is not expected. Should be 'I am a JS Confirm', but it is 'I am a JS Confirm[Fail]' expected [true] but found [false],result is not expected. Should be 'You clicked: Cancel', but it is 'You clicked: Cancel[Fail]' expected [true] but found [false]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at com.james.training.selenium_project.uielementspagetests.AlertsSoftAssertsTests.jsDismissTest(AlertsSoftAssertsTests.java:86)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.base/java.lang.reflect.Method.invoke(Method.java:566)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- jsDismissTest -->
</testsuite> <!-- com.james.training.selenium_project.uielementspagetests.AlertsSoftAssertsTests -->
